spring:
  application:
    name: store
stripe:
  api-url: https://api.stripe.com
  enabled: true
  timeout: 60
  supported-currencies: USD,EUR,GBP
payment-gateway: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761